name: SrainEventPack
version: "0.2.2"
api-version: "1.19"
main: com.github.srain3.sep.SEP
author: Srain3
website: "https://github.com/Srain3/SrainEventPack"

commands:
  treasure:
    description: "宝探しイベント用コマンド"
    permission: "sep.treasure"

permissions:
  sep.treasure:
    description: "宝探しイベント用コマンドの権限"
    default: op